LUSEI <- function(code, kind) {
    # determine if a LUSEI code is a specified level for sure
    # ARGS
    # code : integer vector
    # kind : chr scalar

    x <-
    switch(kind,
           residential                     = code == 100,  # (not elsewhere classified)
           townhouse                       = code == 102,  # or rowhouse
           hotel                           = code == 103,  # or apartment
           apartment                       = code == 106,
           cabin                           = code == 109,
           cooperative                     = code == 111,
           condominium                     = code == 112,
           condominium.project             = code == 113,
           common.area                     = code == 114,
           duplex                          = code == 115,
           mid.rise.condominium            = code == 116,
           high.rise.condominium           = code == 117,
           fraternity.house                = code == 118,  # or sorority house
           residence.hall                  = code == 119,  # or dormitories
           hotel                           = code == 127,
           resort.hotel                    = code == 130,
           multi.family.unit.10.units.plus = code == 131,
           multi.family.unit.10.units.less = code == 132,
           multi.family.dwelling           = code == 133,
           mixed.complex                   = code == 134,
           mobile.home.lot                 = code == 135,
           mobile.home.park                = code == 136,
           mobile.home.pp                  = code == 137,
           mombile.home.coop               = code == 138,
           motel                           = code == 142,
           pud                             = code == 148,
           quadruplex                      = code == 151,
           group.quarters                  = code == 155,
           orphanage                       = code == 156,
           nursing.home                    = code == 157,
           rural.homesite                  = code == 160,
           sfr                             = code == 163,  # single family residential
           transient.lodging               = code == 164,
           triplex                         = code == 165,
           time.share                      = code == 167,
           time.share.condo                = code == 199,
           commercial                      = code == 200,  # not elswhere classified
           air.rights                      = code == 201,
           multiple.uses                   = code == 202,
           auto.equipment                  = code == 203,
           auto.repair                     = code == 204,
           auto.sales                      = code == 205,
           salvage.imprv                   = code == 207,
           auto.wrecking                   = code == 208,
           business.park                   = code == 209,
           carwash                         = code == 210,
           commercial.building             = code == 211,
           cemetery                        = code == 212,
           commercial.condominium          = code == 213,
           convalescent.hospital           = code == 214,
           convention.center               = code == 215,
           department.store                = code == 217,
           facilities                      = code == 218,
           store.franchise                 = code == 220,
           fast.food.franchise             = code == 221,
           fin                             = code == 221, # or insurance or real estate
           financial.building              = code == 223,
           funeral.home                    = code == 225,
           garage                          = code == 226,
           greenhouse                      = code == 229,
           hospital                        = code == 230,
           kennel                          = code == 234,
           animal.hospital                 = code == 235,  # or vet
           loft.building                   = code == 236,
           medical.building                = code == 237,
           medical.condo                   = code == 238,
           laboratory                      = code == 239,
           laundromat                      = code == 240,
           nightclub                       = code == 242,
           bar                             = code == 243,
           office.building                 = code == 244,
           office.and.residential          = code == 245,
           office.and.showroom             = code == 246,
           office.condo                    = code == 247,
           converted.residence             = code == 248,
           misc.improvements               = code == 249,
           pre.fabricated.bldg             = code == 250,
           misc.building                   = code == 251,
           parking.lot                     = code == 252,
           parking.structure               = code == 255,
           produce.market                  = code == 257,
           public.storage                  = code == 258,
           restaurant.building             = code == 261,
           restaurant.drive.in             = code == 262,
           service.station                 = code == 266,
           service.station.market          = code == 268,
           misc.commercial.services        = code == 269,
           shopping.center                 = code == 270,
           strip.commercial.center         = code == 273,
           apparel                         = code == 276,
           store.buildings                 = code == 278,
           stores.and.offices              = code == 279,
           stores.and.residential          = code == 281,
           retail.trade                    = code == 282,
           supermarket                     = code == 283,
           food.stores                     = code == 284,
           tavern                          = code == 285,
           wholesale                       = code == 286,
           leased.land.bldg                = code == 290,
           leased.land.bldg.2              = code == 299,
           industrial                      = code == 300,  # not elsewhere classified
           commerical.industrial           = code == 301,
           brewery                         = code == 302,
           bulk.plant                      = code == 303,
           cannery                         = code == 304,
           chemical                        = code == 308,
           textile                         = code == 309,  # or clothes or carpet industry
           paper                           = code == 310,  # and allied industry
           dump.site                       = code == 311,
           durable.goods                   = code == 312,
           non.durable.goods               = code == 313,
           food.processor                  = code == 316,
           grain.elevator                  = code == 318,
           heavy.industrial                = code == 320,
           industrial.condominium          = code == 321,
           industrial.park                 = code == 322,
           industrial.plant                = code == 323,
           light.industrial                = code == 324,
           lumber.yard                     = code == 326,
           lumber.mill                     = code == 328,
           metal.product                   = code == 331,
           mineral.rights                  = code == 333,
           mineral.processing              = code == 334,
           mini.warehouse                  = code == 336,
           multi.tenant.industrial         = code == 338,
           packing                         = code == 342,
           petroleum                       = code == 344,
           mine                            = code == 349,  # or quarry
           r.and.d.facility                = code == 352,
           technological.industry          = code == 353,
           shipyard                        = code == 354,
           stockyard                       = code == 356,
           storage                         = code == 358,
           storage.tanks                   = code == 361,
           warehouse                       = code == 364,
           winery                          = code == 366,
           winery.2                        = code == 399,
           vacant.land                     = code == 400,  # not elsewhere classified
           marshland                       = code == 401,
           flood.plain                     = code == 402,
           barren.land                     = code == 410,
           commercial.acreage              = code == 415,
           commercial.lot                  = code == 420,
           commmon.land                    = code == 421,  # possibly a park
           desert                          = code == 425,
           agriculural.land                = code == 430,
           industrial.acreage              = code == 435,
           industrial.lot                  = code == 440,
           mountainous.land                = code == 445,
           natural.resources               = code == 446,
           multi.family.acreage            = code == 450,
           multi.family.lot                = code == 452,
           open.space                      = code == 453,
           vacant.mobile.home              = code == 454,
           recreational.acreage            = code == 455,
           residential.acreage             = code == 460,
           residential.lot                 = code == 465,
           waste.land                      = code == 480,
           vacant.lmtd.dev.potential       = code == 481,  # or no dev potential
           wildlife.refuge                 = code == 490,
           wildlife.refuge.2               = code == 499,
           agricultural                    = code == 500,  # not elsewhere classified
           livestock                       = code == 501,
           nursery                         = code == 502,  # or horticulture
           agricultural.plant              = code == 505,
           ranch                           = code == 509,
           animal.farm                     = code == 510,
           farms                           = code == 511,
           avocado.grove                   = code == 512,
           citrus.grove                    = code == 514,
           dairy.farm                      = code == 515,
           fallow.land                     = code == 520,
           field.and.seed                  = code == 530,
           fisheries                       = code == 533,
           forest                          = code == 540,
           greenbelt                       = code == 542,
           orchard                         = code == 550,
           pasture                         = code == 560,
           poultry.ranch                   = code == 562,
           truck.crops                     = code == 570,
           vineyard                        = code == 575,
           vineyard.2                      = code == 599,
           public                          = code == 600,  # not elsewhere classified
           tax.exempt                      = code == 601,  # PARK?
           state.property                  = code == 602,
           country.property                = code == 603,
           municipal.property              = code == 604,
           police.fire.civil.defence       = code == 605,
           us.postal.service               = code == 606,
           embassies                       = code == 607,  # or chanceries
           correction.facility             = code == 609,
           community.center                = code == 610,
           historic.district               = code == 611,
           federal.property                = code == 614,
           federal.building                = code == 615,
           indian.reservation              = code == 618,
           art                             = code == 620,
           military.building               = code == 630,
           possessory.interest             = code == 640,
           school                          = code == 650,
           nursery.school                  = code == 652,
           high.school                     = code == 654,
           private.school                  = code == 655,
           vocational.trade.school         = code == 656,
           educational.service             = code == 660,
           secondary.educational.school    = code == 664,
           public.school.1                 = code == 665,
           public.school.2                 = code == 670,
           charitable.organization         = code == 671,
           religious                       = code == 675,
           university                      = code == 680,
           nature.facility                 = code == 690,
           zoo                             = code == 699,
           recreational                    = code == 700,  # not elswhere classified
           casino                          = code == 701,
           amphitheatre                    = code == 703,
           amusement.arcade                = code == 706,
           amusement.park                  = code == 709,
           auditorium                      = code == 712,
           bowling.alley                   = code == 721,
           billiard.hall                   = code == 724,
           club                            = code == 725,
           country.club                    = code == 727,
           health.club                     = code == 728,
           dance.hall                      = code == 733,
           golf.course                     = code == 742,
           golf.range                      = code == 745,
           gymnasium                       = code == 750,
           lake.river.beach                = code == 754,
           marina.facility.recreational    = code == 755,
           park                            = code == 757,   # PARK!
           race.track                      = code == 745,
           tennis.court                    = code == 769,  # or tacquet court
           tennis.club                     = code == 770,
           rv.park                         = code == 775,
           skating.rink                    = code == 780,
           stadium                         = code == 784,
           stable                          = code == 787,
           swimming.pool                   = code == 790,
           drive.in.theater                = code == 795,
           theater                         = code == 796,
           tourist.attraction              = code == 797,  # or exhibits
           library.museum                  = code == 798,
           transport                       = code == 800,  # not elsewhere classified
           communication.facility          = code == 801,
           aircraft.facility               = code == 806,
           airport                         = code == 808,
           electrical.facility             = code == 818,
           gas.production                  = code == 830,
           marine.facility.commercial      = code == 839,
           port.harbor                     = code == 850,
           railroad.facility               = code == 860,
           recording.studio                = code == 863,
           radio.facility                  = code == 864,
           easement                        = code == 867,
           telephone.facility              = code == 872,  # or communication
           tv.facility                     = code == 875,
           transport.facility              = code == 877,
           truck.terminal                  = code == 879,
           utilities                       = code == 880,
           waste.disposal                  = code == 883,
           well.water                      = code == 885,
           well.gas.oil                    = code == 886,
           pipeline                        = code == 887,
           well.gas.oil.2                  = code == 889,
           type.unknown                    = code == 999,
           # composite types
           any.school                      = (code >= 650) & (code <= 665),  # not universities

           # default
           ...                             = stop(sprintf('bad kind = %s', kind))
           )

    result <- ifelse(is.na(x), FALSE, x)
    result
}
