OUTPUT=../data/v6/output
FILEBASE=parcels-sfr-geocoded
FACTORS="ZONING VIEW LOCATION.INFLUENCE.CODE AIR.CONDITIONING.CODE CONDITION.CODE CONSTRUCTION.TYPE.CODE \
EXTERIOR.WALLS.CODE FIREPLACE.INDICATOR.FLAG FIREPLACE.TYPE.CODE FOUNDATION.CODE FLOOR.CODE FRAME.CODE \
GARAGE.CODE HEATING.CODE PARKING.TYPE.CODE POOL.FLAG POOL.CODE QUALITY.CODE ROOF.COVER.CODE \
ROOF.TYPE.CODE STYLE.CODE SEWER.CODE WATER.CODE"
luajit program_csv_to_ser_NamedMatrix.lua \
    --input $OUTPUT/$FILEBASE.csv \
    --output $OUTPUT/$FILEBASE.serialized-NamedMatrix \
    --factors $FACTORS
